intercept-console-error.ts:41 Cannot render a sync or defer <script> outside the main document without knowing its order. Try adding async="" or moving it into the root <head> tag.
intercept-console-error.ts:41 In HTML, <script> cannot be a child of <html>.
This will cause a hydration error.

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/article/a..." notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
>                     <html lang="en" suppressHydrationWarning={true}>
                        <Script id="import-map" strategy="beforeInte..." type="importmap" ...>
>                         <script nonce={undefined} dangerouslySetInnerHTML={{__html:"(self.__ne..."}}>
                        ...
                    ...
        ...
intercept-console-error.ts:41 <html> cannot contain a nested <script>.
See this log for the ancestor stack trace.
25
intercept-console-error.ts:41 Cannot render a sync or defer <script> outside the main document without knowing its order. Try adding async="" or moving it into the root <head> tag.
Geist_Variable-s.p.f406b17f.woff2:1
 Failed to load resource: the server responded with a status of 403 (Forbidden)
468
intercept-console-error.ts:41 Cannot render a sync or defer <script> outside the main document without knowing its order. Try adding async="" or moving it into the root <head> tag.
firebase-config.ts:39 Firebase initialized successfully.
intercept-console-error.ts:41 Cannot render a sync or defer <script> outside the main document without knowing its order. Try adding async="" or moving it into the root <head> tag.
firebase-storage.ts:160 Article aHR0cHM6Ly93d3cubnByLm9yZy8yMDI1LzA1LzAzL254LXMxLTUzODQ5NDEvYXhvbG90bHMtbWV4aWNhbi13ZXRsYW5kcw retrieved successfully.
Avatar.tsx:99 Attempting to dynamically import TalkingHead...
intercept-console-error.ts:41 Failed to dynamically import or initialize TalkingHead: Error: Cannot find module 'talkinghead'
    at Avatar.tsx:105:37
    at Avatar.useEffect.loadAndInit (Avatar.tsx:105:37)
    at Avatar.useEffect (Avatar.tsx:126:5)